service: demo-line-app

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: flask/main.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'